### ISSUE TITLE
EasyCustomTabsIntentBuilder always requires a connection

### ISSUE THREAD

**Issue by friedger** [novoda/simplechromecustomtabs#1]
Users might not want to open a connection, but only theme the tab.
Make it optional and use `CustomTabsIntent.Builder ()` when `EasyCustomTabsIntentBuilder.useSameBrowser` was not called.

Or should it be `useSameTab` ? Needs better understanding of the different constructors.

**Comment by blundell** [comment]
closed because what? ... please write why on closed issues
