### ISSUE TITLE
no java-rx

### ISSUE THREAD

**Issue by alosdev** [novoda/simplechromecustomtabs#10]
It would be nice, that the developer using you library is not forced to use RX if you just use it internally.

**Comment by juankysoriano** [comment]
Hello Hassan,

The decision about wether to make use of an Rx approach for this library wasn't trivial, we have good reasons for it and we it is very unlikely that we'll change that in the near future.

Out of curiosity, are you worried about hitting the 64k method limit? If that's the case I encourage you see wether or not proguard could work for you. What's your main concern about it?

Thank you for your interest on `SimpleChromeCustomTabs`.

**Comment by alosdev** [comment]
One is hitting the 64K limit, the other is code architecture. I think the approach over proguard is at that point wrong. Did you had any problem, if I decouple the rx part into an plugin, so the user of the library has the own choice?

**Comment by juankysoriano** [comment]
@alosdev you might be right, that's why I reopened the issue. We might take a look to using android apis from background tasks at some point.

**Comment by juankysoriano** [comment]
Solved in #11
