### ISSUE TITLE
Missing a Callback on SimpleChromeCustomTabs.connectTo(Activity activity)

### ISSUE THREAD

**Issue by juankysoriano** [novoda/simplechromecustomtabs#7]
Even if `SimpleChromeCustomTabs` allows to set a navigation fallback if something goes wrong, it should also include a way to notify that the connection failed when `SimpleChromeCustomTabs,connectTo(Activity activity)` is called. This provides the client with an early feedback of any potential problems.

**Comment by blundell** [comment]
closed because what? ... please write why on closed issues
